### PR TITLE
Add support for Logitech G710+

### PR DESCRIPTION
**Pull request by nirenjan**

### CODE REVIEW

**Comment by zocker-160** [comment]
thank you for this <3

changes look good to me, could you test it and confirm that it is working?

**Comment by nirenjan** [comment]
I checked it, but there is one issue lacking, which is that the G keys report 1 through 6 by default. I tried to send the command to disable the defaults of those, but it doesn't seem to take effect. Looking at your source code, it looks like I need the `g810-led` program, which doesn't support the G710+ keyboard (at least as of now).

**Comment by zocker-160** [comment]
Do you know what driver does the mapping to the 1-9 keys?

> Looking at your source code, it looks like I need the g810-led program, which doesn't support the G710+ keyboard (at least as of now).

The `g810-led` program is not required, I do call `g810-led -gkm 1` however, because IF it is installed, then it will map the G-keys to F1 - F6 (or F9 respectively), and I can disable that by calling the command above.

If you don't have that software installed, then the default mapping come from a different driver.

**Comment by nirenjan** [comment]
There's no driver. The keyboard defaults the G keys to send 1 through 6 for the G keys in hardware when plugged in. I need to send the HID report `\x09\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00` to interface 1 to disable the G keys.

I have some local code that uses hidapi to do that, but I haven't published it on Github yet.

**Comment by zocker-160** [comment]
ah understood, so the keyboard does it. hmmm.
Interface 1 you say, so that is the same I use for reading the incoming data?

So this should be fixable by writing the raw data you wrote to that same interface?

**Comment by nirenjan** [comment]
Ideally, but I couldn't figure out why the raw data didn't work... Let me upload the second patch that I had for that, you can review that as well.

**Comment by zocker-160** [comment]
looking good, is there anything more I need to know?

If not I will merge and BIG thank you from my side!

**Comment by nirenjan** [comment]
Nothing else I can think of. Glad I could help.

**Pull request merged**
